sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: CXX_STD=11 TOOLSET=g++-4.8 SIMD_EXT=-msse2

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: CXX_STD=11 TOOLSET=g++-4.8 SIMD_EXT=-mavx

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: CXX_STD=11 TOOLSET=g++-4.9 SIMD_EXT=-msse2

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: CXX_STD=11 TOOLSET=g++-4.9 SIMD_EXT=-mavx

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: CXX_STD=11 TOOLSET=g++-5 SIMD_EXT=-msse2

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: CXX_STD=14 TOOLSET=g++-5 SIMD_EXT=-msse2

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: CXX_STD=11 TOOLSET=g++-5 SIMD_EXT=-mavx

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: CXX_STD=11 TOOLSET=clang++-3.5 SIMD_EXT=-msse2

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: CXX_STD=11 TOOLSET=clang++-3.5 SIMD_EXT=-mavx

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: CXX_STD=11 TOOLSET=clang++-3.6 SIMD_EXT=-msse2

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: CXX_STD=11 TOOLSET=clang++-3.6 SIMD_EXT=-mavx

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: CXX_STD=14 TOOLSET=clang++-3.6 SIMD_EXT=-msse2

    - os: osx
      compiler: clang
      env: CXX_STD=11 TOOLSET=clang++ SIMD_EXT=-msse2

# Install boost
before_install:
  - bash ./script/travis/install.sh
  - export BOOST_ROOT="$HOME/boost-trunk"

# Prepare build
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET -DCMAKE_CXX_FLAGS="$SIMD_EXT -I$HOME/dispatch/include" -DSIMD_EXT=$SIMD_EXT -DCXX_STD=$CXX_STD -DTOOLSET=$TOOLSET

# Build unit and run test
script:
  - make -k unit
  - ctest -D Experimental
